describe('Solo Mode journey testing', () => {

  beforeEach(function() {
    cy.visit('http://localhost:3000')
  })

  it('front page renders', function() {
    cy.contains('Play')
    cy.contains('Profile')
    cy.contains('About')
  })

  it('visit solo', function() {
    cy.contains('Profile').click()
    cy.contains('Nothing in Journey yet!').should('be.visible')
    cy.contains('Your daily Solo Questions are ready').should('be.visible')
    cy.contains('back').click()
    cy.contains('Play').click()
    cy.contains('Solo').click()
    cy.contains('Start').click()
    cy.contains('close').click()
    cy.contains('help').click()
    cy.contains('close').click()
    cy.contains('solo lv 1').should('be.visible')
    cy.get('textarea').type('reflection_1st')
    cy.get('button').click()
    cy.contains('Response submitted!').should('be.visible')
    cy.contains('back').click()
    cy.contains('Profile').click()
    cy.contains('solo lv 1').click()
    cy.contains('reflection_1st').should('be.visible')
    cy.contains('back').click()
    cy.contains('back').click()
    cy.contains('Play').click()
    cy.contains('Solo').click()
    cy.contains('Start').click()
    cy.contains('solo lv 1').should('be.visible')
    cy.get('textarea').type('reflection_2nd')
    cy.get('button').click()
    cy.contains('Loading').should('be.visible')
    cy.contains('solo pic').should('be.visible')
    cy.get('.selectable').first().click()
    cy.get('button').scrollIntoView().click()
    cy.get('textarea').type('reflection_pic')
    cy.get('button').click()
    cy.contains('back').click()
    cy.contains('Play').click()
    cy.contains('Solo').click()
    cy.contains('Come back tomorrow').should('be.visible')
    cy.get('.menu__linkbutton--back').click()
    cy.contains('Profile').click()
    cy.contains('reflection_pic').click()
    cy.contains('reflection_pic').should('be.visible')
  })

  it('solo next day', function() {
    cy.contains('Profile').click()
    cy.contains('Nothing in Journey yet!').should('be.visible')
    cy.contains('Your daily Solo Questions are ready').should('be.visible')
    cy.contains('back').click()
    cy.contains('Play').click()
    cy.contains('Solo').click()
    cy.contains('Start').click()
    cy.contains('close').click()
    cy.contains('help').click()
    cy.contains('close').click()
    cy.contains('solo lv 1').should('be.visible')
    cy.get('textarea').type('reflection_1st')
    cy.get('button').click()
    cy.contains('Response submitted!').should('be.visible')
    cy.contains('back').click()
    cy.contains('Profile').click()
    cy.contains('solo lv 1').click()
    cy.contains('reflection_1st').should('be.visible')
    cy.contains('back').click()
    cy.contains('back').click()
    cy.contains('Play').click()
    cy.contains('Solo').click()
    cy.contains('Start').click()
    cy.contains('solo lv 1').should('be.visible')
    cy.get('textarea').type('reflection_2nd')
    cy.get('button').click()
    cy.contains('Loading').should('be.visible')
    cy.contains('solo pic').should('be.visible')
    cy.get('.selectable').first().click()
    cy.get('button').scrollIntoView().click()
    cy.get('textarea').type('reflection_pic')
    cy.get('button').click()
    cy.contains('back').click()
    cy.contains('Play').click()
    cy.contains('Solo').click()
    cy.contains('Come back tomorrow').should('be.visible')
    cy.get('.menu__linkbutton--back').click()
    cy.contains('Profile').click()
    cy.contains('reflection_pic').click()
    cy.contains('reflection_pic').should('be.visible')
    cy.contains('back').click()
    cy.contains('reflection_1st')
    cy.contains('reflection_2nd')
    cy.get('Your daily Solo Questions are ready').should('not.exist')

    const yesterday = new Date(new Date().getTime() - (24 * 60 * 60 * 1000));
    cy.setLocalStorage('solo', JSON.stringify(yesterday))

    cy.contains('back').click()
    cy.contains('Play').click()
    cy.contains('Solo').click()
    cy.contains('Start').click()
    cy.contains('solo lv 1').should('be.visible')
    cy.get('textarea').type('reflection_4th')
    cy.get('button').click()
    cy.contains('solo lv 1').should('be.visible')
    cy.get('textarea').type('reflection_5th')
    cy.get('button').click()
    cy.contains('Loading').should('be.visible')
    cy.contains('solo pic').should('be.visible')
    cy.get('.selectable').first().click()
    cy.get('button').scrollIntoView().click()
    cy.get('textarea').type('reflection_pic_6th')
    cy.get('button').click()
    cy.contains('back').click()
    cy.contains('Play').click()
    cy.contains('Solo').click()
    cy.contains('Come back tomorrow').should('be.visible')
    cy.get('.menu__linkbutton--back').click()
    cy.contains('Profile').click()
    cy.contains('reflection_1st').should('exist')
    cy.contains('reflection_2nd').should('exist')
    cy.contains('reflection_pic').should('exist')
    cy.contains('reflection_4th').should('exist')
    cy.contains('reflection_5th').should('exist')
    cy.contains('reflection_pic_6th').should('exist')
  })
})