name: Run CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  ci:
    name: Run CI
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: '12.x'
        - name: npm install 
          run: npm install  
        - name: lint
          run: npm run lint
